version: '3.4'

services:
  expressweb1:
    image: expressweb1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
